<a href="https://colab.research.google.com/github/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/blob/main/STTP_DAY1_RAW_DATA_TO_REFINED_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Read TEACHERS_RAW Data

import pandas as pd

# The 'r' before the string treats backslashes as a raw string literal
df = pd.read_csv("https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-TEACHERS-RAW.csv")

# View the column names
print(df.columns)

Index(['TID', 'TNAME', 'TAGE', 'TMRF', 'TSUB', 'TSAL', 'TACTIVE', 'TDESIG'], dtype='object')

In [ ]:
df.head()

   TID TNAME  TAGE TMRF      TSUB     TSAL TACTIVE TDESIG
0    1    T1  30.0    M     S1,S2  30000.0       y    JAP
1    2    T2  35.0    M        S3  35000.0       y    SAP
2    3    T3  40.0    M     S2,S3  40000.0       y      P
3    4    T4  45.0    F     S3,S4  45000.0       y     SP
4    5    T5  50.0    F  S1,S2,S4  50000.0       y   JPOP

In [ ]:

# Read STUDENTS_RAW Data

import pandas as pd

# The 'r' before the string treats backslashes as a raw string literal
df = pd.read_csv("https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-STUDENTS-RAW.csv")

# View the column names
print(df.columns)

Index(['SID', 'SNAME', 'SAGE', 'SMRF', 'SSUB', 'SMARKS'], dtype='object')

In [ ]:
df.head()

   SID SNAME  SAGE SMRF   SSUB  SMARKS
0    1    S1   NaN    M  S1,S2    60.0
1    2    S2  20.0    M  S3,S4    70.0
2    3    S3  21.0    F  S1,S2    80.0
3    4    S4  22.0    F  S3,S4    90.0
4    5    S5  19.0    M  S1,S2    60.0

In [ ]:
# Loading NULL VALUE TEACHERS_RAW data

import pandas as pd

# 1. Load the CSV file into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-TEACHERS-RAW.csv')

# print(df)

# 2. Filter out rows containing at least one missing value
rows_with_nan = df[df.isna().any(axis=1)]

# 3. Display the missing rows
print(rows_with_nan)

    TID TNAME  TAGE TMRF      TSUB     TSAL TACTIVE TDESIG
5     6    T6   NaN    F  S2,S3,S4  55000.0       y   SPOP
11   12   T12  50.0    F  S2,S3,S4      NaN       y   JPOP
18   19   T19  50.0    M     S1,S4  50000.0       y    NaN
26   27   T27  55.0  NaN     S1,S4  55000.0       n   SPOP
34   35   T35  60.0    F       NaN  60000.0       y    HOD
46   47   NaN  50.0    F     S1,S4  50000.0       y   JPOP

In [ ]:
# Loading NULL VALUE STUDENTS_RAW data

import pandas as pd

# 1. Load the CSV file into a DataFrame
df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-STUDENTS-RAW.csv')

## print(df)

# 2. Filter out rows containing at least one missing value
rows_with_nan = df[df.isna().any(axis=1)]

# 3. Display the missing rows
print(rows_with_nan)

     SID SNAME  SAGE SMRF   SSUB  SMARKS
0      1    S1   NaN    M  S1,S2    60.0
6      7    S7  21.0    F  S1,S2     NaN
14    15   S15   NaN    F  S1,S2    80.0
20    21   S21  19.0    M    NaN    60.0
25    26   NaN  20.0    M  S1,S2    70.0
30    31   S31  21.0    F    NaN    80.0
36    37   S37  19.0    M  S3,S4     NaN
40    41   S41   NaN    M  S3,S4    60.0
47    48   S48  22.0    F    NaN    90.0
54    55   S55   NaN    F  S1,S2    80.0
58    59   S59  21.0    F  S1,S2     NaN
67    68   S68   NaN    F  S3,S4    90.0
73    74   S74  20.0    M  S1,S2     NaN
82    83   S83   NaN    F  S3,S4    80.0
90    91   S91  21.0    F  S3,S4     NaN
100  101  S101   NaN    M  S1,S2    60.0
114  115  S115  21.0    F  S1,S2     NaN
124  125  S125   NaN    M  S3,S4    60.0
144  145  S145  19.0    M  S1,S2     NaN

In [ ]:
# LOAD TEACHERS_RAW DATA and Do one-hot encoding

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-TEACHERS-RAW.csv')

# df = pd.DataFrame(data)

print("Original Data:")

print(df)

encoded_df = pd.get_dummies(
    df,
    columns=['TSUB'],
    drop_first=True
)

print("\nOne-Hot Encoded Data:")
print(encoded_df)

Original Data:
    TID TNAME  TAGE TMRF      TSUB     TSAL TACTIVE TDESIG
0     1    T1  30.0    M     S1,S2  30000.0       y    JAP
1     2    T2  35.0    M        S3  35000.0       y    SAP
2     3    T3  40.0    M     S2,S3  40000.0       y      P
3     4    T4  45.0    F     S3,S4  45000.0       y     SP
4     5    T5  50.0    F  S1,S2,S4  50000.0       y   JPOP
5     6    T6   NaN    F  S2,S3,S4  55000.0       y   SPOP
6     7    T7  60.0    M        S3  60000.0       y    HOD
7     8    T8  30.0    M     S1,S4  30000.0       y    JAP
8     9    T9  35.0    M  S2,S3,S4  35000.0       n    SAP
9    10   T10  40.0    F        S3  40000.0       y      P
10   11   T11  45.0    F     S1,S4  45000.0       y     SP
11   12   T12  50.0    F  S2,S3,S4      NaN       y   JPOP
12   13   T13  55.0    M        S3  55000.0       y   SPOP
13   14   T14  60.0    M     S1,S4  60000.0       y    HOD
14   15   T15  30.0    M        S3  30000.0       y    JAP
15   16   T16  35.0    F        S3  35000.0       y    SAP
16   17   T17  40.0    F     S1,S4  40000.0       y      P
17   18   T18  45.0    F        S3  45000.0       n     SP
18   19   T19  50.0    M     S1,S4  50000.0       y    NaN
19   20   T20  55.0    M     S1,S2  55000.0       y   SPOP
20   21   T21  60.0    M        S3  60000.0       y    HOD
21   22   T22  30.0    F     S2,S3  30000.0       y    JAP
22   23   T23  35.0    F     S3,S4  35000.0       y    SAP
23   24   T24  40.0    F  S1,S2,S4  40000.0       y      P
24   25   T25  45.0    M  S2,S3,S4  45000.0       y     SP
25   26   T26  50.0    M        S3  50000.0       y   JPOP
26   27   T27  55.0  NaN     S1,S4  55000.0       n   SPOP
27   28   T28  60.0    F  S2,S3,S4  60000.0       y    HOD
28   29   T29  30.0    F        S3  30000.0       y    JAP
29   30   T30  35.0    F     S1,S2  35000.0       y    SAP
30   31   T31  40.0    M        S3  40000.0       y      P
31   32   T32  45.0    M     S2,S3  45000.0       y     SP
32   33   T33  50.0    M     S3,S4  50000.0       y   JPOP
33   34   T34  55.0    F  S1,S2,S4  55000.0       y   SPOP
34   35   T35  60.0    F       NaN  60000.0       y    HOD
35   36   T36  30.0    F        S3  30000.0       n    JAP
36   37   T37  35.0    M     S1,S4  35000.0       y    SAP
37   38   T38  40.0    M  S2,S3,S4  40000.0       y      P
38   39   T39  45.0    M        S3  45000.0       y     SP
39   40   T40  50.0    F     S1,S2  50000.0       y   JPOP
40   41   T41  55.0    F        S3  55000.0       y   SPOP
41   42   T42  60.0    F     S2,S3  60000.0       y    HOD
42   43   T43  30.0    M     S3,S4  30000.0       y    JAP
43   44   T44  35.0    M  S1,S2,S4  35000.0       y    SAP
44   45   T45  40.0    M  S2,S3,S4  40000.0       n      P
45   46   T46  45.0    F        S3  45000.0       y     SP
46   47   NaN  50.0    F     S1,S4  50000.0       y   JPOP
47   48   T48  55.0    F  S2,S3,S4  55000.0       y   SPOP
48   49   T49  60.0    M        S3  60000.0       y    HOD
49   50   T50  30.0    F        S3  30000.0       y    JAP

One-Hot Encoded Data:
    TID TNAME  TAGE TMRF     TSAL TACTIVE TDESIG  TSUB_S1,S2,S4  TSUB_S1,S4  \
0     1    T1  30.0    M  30000.0       y    JAP          False       False
1     2    T2  35.0    M  35000.0       y    SAP          False       False
2     3    T3  40.0    M  40000.0       y      P          False       False
3     4    T4  45.0    F  45000.0       y     SP          False       False
4     5    T5  50.0    F  50000.0       y   JPOP           True       False
5     6    T6   NaN    F  55000.0       y   SPOP          False       False
6     7    T7  60.0    M  60000.0       y    HOD          False       False
7     8    T8  30.0    M  30000.0       y    JAP          False        True
8     9    T9  35.0    M  35000.0       n    SAP          False       False
9    10   T10  40.0    F  40000.0       y      P          False       False
10   11   T11  45.0    F  45000.0       y     SP          False        True
11   12   T12  50.0    F      NaN       y   JPOP          False       False
12   13   T13  55.0    M  55000.0       y   SPOP          False       False
13   14   T14  60.0    M  60000.0       y    HOD          False        True
14   15   T15  30.0    M  30000.0       y    JAP          False       False
15   16   T16  35.0    F  35000.0       y    SAP          False       False
16   17   T17  40.0    F  40000.0       y      P          False        True
17   18   T18  45.0    F  45000.0       n     SP          False       False
18   19   T19  50.0    M  50000.0       y    NaN          False        True
19   20   T20  55.0    M  55000.0       y   SPOP          False       False
20   21   T21  60.0    M  60000.0       y    HOD          False       False
21   22   T22  30.0    F  30000.0       y    JAP          False       False
22   23   T23  35.0    F  35000.0       y    SAP          False       False
23   24   T24  40.0    F  40000.0       y      P           True       False
24   25   T25  45.0    M  45000.0       y     SP          False       False
25   26   T26  50.0    M  50000.0       y   JPOP          False       False
26   27   T27  55.0  NaN  55000.0       n   SPOP          False        True
27   28   T28  60.0    F  60000.0       y    HOD          False       False
28   29   T29  30.0    F  30000.0       y    JAP          False       False
29   30   T30  35.0    F  35000.0       y    SAP          False       False
30   31   T31  40.0    M  40000.0       y      P          False       False
31   32   T32  45.0    M  45000.0       y     SP          False       False
32   33   T33  50.0    M  50000.0       y   JPOP          False       False
33   34   T34  55.0    F  55000.0       y   SPOP           True       False
34   35   T35  60.0    F  60000.0       y    HOD          False       False
35   36   T36  30.0    F  30000.0       n    JAP          False       False
36   37   T37  35.0    M  35000.0       y    SAP          False        True
37   38   T38  40.0    M  40000.0       y      P          False       False
38   39   T39  45.0    M  45000.0       y     SP          False       False
39   40   T40  50.0    F  50000.0       y   JPOP          False       False
40   41   T41  55.0    F  55000.0       y   SPOP          False       False
41   42   T42  60.0    F  60000.0       y    HOD          False       False
42   43   T43  30.0    M  30000.0       y    JAP          False       False
43   44   T44  35.0    M  35000.0       y    SAP           True       False
44   45   T45  40.0    M  40000.0       n      P          False       False
45   46   T46  45.0    F  45000.0       y     SP          False       False
46   47   NaN  50.0    F  50000.0       y   JPOP          False        True
47   48   T48  55.0    F  55000.0       y   SPOP          False       False
48   49   T49  60.0    M  60000.0       y    HOD          False       False
49   50   T50  30.0    F  30000.0       y    JAP          False       False

    TSUB_S2,S3  TSUB_S2,S3,S4  TSUB_S3  TSUB_S3,S4
0        False          False    False       False
1        False          False     True       False
2         True          False    False       False
3        False          False    False        True
4        False          False    False       False
5        False           True    False       False
6        False          False     True       False
7        False          False    False       False
8        False           True    False       False
9        False          False     True       False
10       False          False    False       False
11       False           True    False       False
12       False          False     True       False
13       False          False    False       False
14       False          False     True       False
15       False          False     True       False
16       False          False    False       False
17       False          False     True       False
18       False          False    False       False
19       False          False    False       False
20       False          False     True       False
21        True          False    False       False
22       False          False    False        True
23       False          False    False       False
24       False           True    False       False
25       False          False     True       False
26       False          False    False       False
27       False           True    False       False
28       False          False     True       False
29       False          False    False       False
30       False          False     True       False
31        True          False    False       False
32       False          False    False        True
33       False          False    False       False
34       False          False    False       False
35       False          False     True       False
36       False          False    False       False
37       False           True    False       False
38       False          False     True       False
39       False          False    False       False
40       False          False     True       False
41        True          False    False       False
42       False          False    False        True
43       False          False    False       False
44       False           True    False       False
45       False          False     True       False
46       False          False    False       False
47       False           True    False       False
48       False          False     True       False
49       False          False     True       False

In [ ]:
# LOAD STUDENTS_RAW DATA and Do one-hot encoding

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-STUDENTS-RAW.csv')

# df = pd.DataFrame(data)

print("Original Data:")
print(df)

encoded_df = pd.get_dummies(
    df,
    columns=['SSUB'],
    drop_first=True
)

print("\nOne-Hot Encoded Data:")
print(encoded_df)

Original Data:
     SID SNAME  SAGE SMRF   SSUB  SMARKS
0      1    S1   NaN    M  S1,S2    60.0
1      2    S2  20.0    M  S3,S4    70.0
2      3    S3  21.0    F  S1,S2    80.0
3      4    S4  22.0    F  S3,S4    90.0
4      5    S5  19.0    M  S1,S2    60.0
..   ...   ...   ...  ...    ...     ...
145  146  S146  20.0    M  S3,S4    70.0
146  147  S147  21.0    F  S1,S2    80.0
147  148  S148  22.0    F  S3,S4    90.0
148  149  S149  19.0    M  S1,S2    60.0
149  150  S150  20.0    M  S3,S4    70.0

[150 rows x 6 columns]

One-Hot Encoded Data:
     SID SNAME  SAGE SMRF  SMARKS  SSUB_S3,S4
0      1    S1   NaN    M    60.0       False
1      2    S2  20.0    M    70.0        True
2      3    S3  21.0    F    80.0       False
3      4    S4  22.0    F    90.0        True
4      5    S5  19.0    M    60.0       False
..   ...   ...   ...  ...     ...         ...
145  146  S146  20.0    M    70.0        True
146  147  S147  21.0    F    80.0       False
147  148  S148  22.0    F    90.0        True
148  149  S149  19.0    M    60.0       False
149  150  S150  20.0    M    70.0        True

[150 rows x 6 columns]

In [ ]:
## To check for duplicates in TEACHERS_RAW Data
import pandas as pd

# Load the CSV data
df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-TEACHERS-RAW.csv')

# Get a boolean mask of duplicate rows (True means it is a duplicate)
duplicate_mask = df.duplicated()

# Print the total number of duplicate rows
print(f"Total duplicate rows: {duplicate_mask.sum()}")

# Display the actual duplicate rows (keeps the first occurrence)
duplicate_rows = df[duplicate_mask]
print(duplicate_rows)

Total duplicate rows: 0
Empty DataFrame
Columns: [TID, TNAME, TAGE, TMRF, TSUB, TSAL, TACTIVE, TDESIG]
Index: []

In [ ]:
## To check for duplicates in STUDENTS_RAW Data
import pandas as pd

# Load the CSV data
df = pd.read_csv('https://raw.githubusercontent.com/raghurammudumbi-collab/STTP-DATASCIENE-ANALYTICS/refs/heads/main/STTP-STUDENTS-RAW.csv')

# Get a boolean mask of duplicate rows (True means it is a duplicate)
duplicate_mask = df.duplicated()

# Print the total number of duplicate rows
print(f"Total duplicate rows: {duplicate_mask.sum()}")

# Display the actual duplicate rows (keeps the first occurrence)
duplicate_rows = df[duplicate_mask]
print(duplicate_rows)

Total duplicate rows: 0
Empty DataFrame
Columns: [SID, SNAME, SAGE, SMRF, SSUB, SMARKS]
Index: []

In [ ]:
import csv

# Define the data to be written to the CSV file
data = [
    ['Name', 'Age', 'City'],
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

# Specify the file name
filename = 'C:\\raghutest.csv'

# Write data to the CSV file with a pipe delimiter
with open(filename, 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile, delimiter='|')
    csvwriter.writerows(data)

print(f"Data has been written to {filename}")

Data has been written to C:\raghutest.csv